import { buildIntegrationDetailWidgetSpotId, type IntegrationBundle, type IntegrationDefinition } from '@helios/shared/modules/integrations/types'

export const channelImapDetailWidgetSpotId = buildIntegrationDetailWidgetSpotId('channel_imap')

export const integration: IntegrationDefinition = {
  id: 'channel_imap',
  title: 'IMAP + SMTP',
  titleKey: 'integrations.providers.channel_imap.title',
  description:
    'Connect any IMAP-capable mailbox (Fastmail, Proton Bridge, generic IMAP host) for inbound polling and outbound SMTP send.',
  descriptionKey: 'integrations.providers.channel_imap.description',
  category: 'communication',
  hub: 'communication_channels',
  providerKey: 'imap',
  icon: 'mail',
  docsUrl: 'https://datatracker.ietf.org/doc/html/rfc3501',
  package: '@helios/channel-imap',
  version: '0.1.0',
  author: 'Helios Team',
  company: 'Helios',
  license: 'MIT',
  tags: ['email', 'imap', 'smtp', 'polling', 'communication'],
  detailPage: {
    widgetSpotId: channelImapDetailWidgetSpotId,
  },
  apiVersions: [
    {
      id: 'rfc3501+rfc5321',
      label: 'IMAP4 (RFC3501) + SMTP (RFC5321)',
      status: 'stable',
      default: true,
      changelog: 'Initial IMAP4/SMTP baseline. UIDVALIDITY+UIDNEXT polling, SMTP STARTTLS+SSL.',
    },
  ],
  credentials: {
    fields: [
      {
        key: 'imapHost',
        label: 'IMAP host',
        labelKey: 'integrations.providers.channel_imap.credentials.imapHost.label',
        type: 'text',
        required: true,
        placeholder: 'imap.fastmail.com',
        helpText: 'Hostname of the IMAP server. Typically the same hostname your mail client uses.',
        helpTextKey: 'integrations.providers.channel_imap.credentials.imapHost.help',
      },
      {
        key: 'imapPort',
        label: 'IMAP port',
        labelKey: 'integrations.providers.channel_imap.credentials.imapPort.label',
        type: 'text',
        required: true,
        placeholder: '993',
        helpText: '993 for IMAPS (TLS) or 143 for STARTTLS.',
        helpTextKey: 'integrations.providers.channel_imap.credentials.imapPort.help',
      },
      {
        key: 'imapTls',
        label: 'IMAP TLS mode',
        labelKey: 'integrations.providers.channel_imap.credentials.imapTls.label',
        type: 'select',
        required: true,
        options: [
          { value: 'tls', label: 'Implicit TLS (port 993)', labelKey: 'integrations.providers.channel_imap.credentials.imapTls.options.tls' },
          { value: 'starttls', label: 'STARTTLS (port 143)', labelKey: 'integrations.providers.channel_imap.credentials.imapTls.options.starttls' },
          { value: 'none', label: 'None (insecure - testing only)', labelKey: 'integrations.providers.channel_imap.credentials.imapTls.options.none' },
        ],
        helpText: 'Prefer implicit TLS. STARTTLS is acceptable. None disables encryption and should only be used inside a private network for testing.',
        helpTextKey: 'integrations.providers.channel_imap.credentials.imapTls.help',
      },
      {
        key: 'imapUser',
        label: 'IMAP username',
        labelKey: 'integrations.providers.channel_imap.credentials.imapUser.label',
        type: 'text',
        required: true,
        helpText: 'Usually your email address.',
        helpTextKey: 'integrations.providers.channel_imap.credentials.imapUser.help',
      },
      {
        key: 'imapPassword',
        label: 'IMAP password (or app password)',
        labelKey: 'integrations.providers.channel_imap.credentials.imapPassword.label',
        type: 'secret',
        required: true,
        helpText: 'Use a per-app password if your provider offers one. Stored encrypted at rest.',
        helpTextKey: 'integrations.providers.channel_imap.credentials.imapPassword.help',
      },
      {
        key: 'smtpHost',
        label: 'SMTP host',
        labelKey: 'integrations.providers.channel_imap.credentials.smtpHost.label',
        type: 'text',
        required: true,
        placeholder: 'smtp.fastmail.com',
      },
      {
        key: 'smtpPort',
        label: 'SMTP port',
        labelKey: 'integrations.providers.channel_imap.credentials.smtpPort.label',
        type: 'text',
        required: true,
        placeholder: '465',
        helpText: '465 for implicit TLS, 587 for STARTTLS.',
        helpTextKey: 'integrations.providers.channel_imap.credentials.smtpPort.help',
      },
      {
        key: 'smtpTls',
        label: 'SMTP TLS mode',
        labelKey: 'integrations.providers.channel_imap.credentials.smtpTls.label',
        type: 'select',
        required: true,
        options: [
          { value: 'tls', label: 'Implicit TLS (port 465)', labelKey: 'integrations.providers.channel_imap.credentials.smtpTls.options.tls' },
          { value: 'starttls', label: 'STARTTLS (port 587)', labelKey: 'integrations.providers.channel_imap.credentials.smtpTls.options.starttls' },
          { value: 'none', label: 'None (insecure - testing only)', labelKey: 'integrations.providers.channel_imap.credentials.smtpTls.options.none' },
        ],
      },
      {
        key: 'smtpUser',
        label: 'SMTP username',
        labelKey: 'integrations.providers.channel_imap.credentials.smtpUser.label',
        type: 'text',
        required: true,
      },
      {
        key: 'smtpPassword',
        label: 'SMTP password (or app password)',
        labelKey: 'integrations.providers.channel_imap.credentials.smtpPassword.label',
        type: 'secret',
        required: true,
        helpText: 'Often the same as the IMAP password; provider-dependent.',
        helpTextKey: 'integrations.providers.channel_imap.credentials.smtpPassword.help',
      },
      {
        key: 'fromAddress',
        label: 'From address',
        labelKey: 'integrations.providers.channel_imap.credentials.fromAddress.label',
        type: 'text',
        required: true,
        placeholder: 'name@example.com',
        helpText: 'Address used as the From header when sending. Must be deliverable by the SMTP server.',
        helpTextKey: 'integrations.providers.channel_imap.credentials.fromAddress.help',
      },
    ],
  },
  healthCheck: { service: 'channelImapHealthCheck' },
}

export const integrations: IntegrationDefinition[] = [integration]
export const bundles: IntegrationBundle[] = []
export const bundle: IntegrationBundle | undefined = undefined
