import type { ModuleInjectionTable } from '@helios/shared/modules/widgets/injection'

const operatingLoopTrigger = {
  widgetId: 'insights.injection.operating-loop-trigger',
  priority: 60,
}

export const injectionTable: ModuleInjectionTable = {
  'data-table:customers.people.list:search-trailing': [operatingLoopTrigger],
  'data-table:customers.companies.list:search-trailing': [operatingLoopTrigger],
  'data-table:customers.deals.list:search-trailing': [operatingLoopTrigger],
  'data-table:sales.orders:search-trailing': [operatingLoopTrigger],
  'data-table:sales.quotes:search-trailing': [operatingLoopTrigger],
  'data-table:inbox_ops.proposals.list:search-trailing': [operatingLoopTrigger],
  'data-table:catalog.products:search-trailing': [operatingLoopTrigger],
  'data-table:catalog.products.list:search-trailing': [operatingLoopTrigger],
  'data-table:wms.inventory.balances:search-trailing': [operatingLoopTrigger],
  'data-table:wms.inventory.reservations:search-trailing': [operatingLoopTrigger],
  'data-table:workflows.instances.list:search-trailing': [operatingLoopTrigger],
  'data-table:workflows.instances.list:header': [operatingLoopTrigger],
  'data-table:workflows.tasks.list:search-trailing': [operatingLoopTrigger],
  'data-table:workflows.tasks.list:header': [operatingLoopTrigger],
  'data-table:projects.list:search-trailing': [operatingLoopTrigger],
  'data-table:projects.milestones.list:search-trailing': [operatingLoopTrigger],
  'data-table:projects.risks.list:search-trailing': [operatingLoopTrigger],
  'data-table:commercial.contracts.list:search-trailing': [operatingLoopTrigger],
  'data-table:commercial.invoices.list:search-trailing': [operatingLoopTrigger],
  'data-table:commercial.payments.list:search-trailing': [operatingLoopTrigger],
  'data-table:commercial.allocations.list:search-trailing': [operatingLoopTrigger],
  'data-table:insights.kpi_targets.list:search-trailing': [operatingLoopTrigger],
  'data-table:insights.kpi.completion:search-trailing': [operatingLoopTrigger],
  'data-table:governance.findings.list:search-trailing': [operatingLoopTrigger],
  'data-table:governance.identity_maps.list:search-trailing': [operatingLoopTrigger],
  'data-table:messages:search-trailing': [operatingLoopTrigger],
  'data-table:staff.team_members:search-trailing': [operatingLoopTrigger],
  'data-table:staff.leave_requests:search-trailing': [operatingLoopTrigger],
  'page:integrations.marketplace:header': [operatingLoopTrigger],
  'detail:customers.person:header': [operatingLoopTrigger],
  'detail:customers.company:header': [operatingLoopTrigger],
  'detail:customers.deal:header': [operatingLoopTrigger],
  'detail:sales.order:header': [operatingLoopTrigger],
  'detail:sales.quote:header': [operatingLoopTrigger],
  'detail:inbox_ops.proposal:header': [operatingLoopTrigger],
  'detail:workflows.instance:header': [operatingLoopTrigger],
  'detail:workflows.task:header': [operatingLoopTrigger],
  'detail:integrations.integration:header': [operatingLoopTrigger],
  'detail:projects.project:header': [operatingLoopTrigger],
  'detail:messages.message:header': [operatingLoopTrigger],
  'detail:staff.leave_request:header': [operatingLoopTrigger],
  'crud-form:catalog.product:header': [operatingLoopTrigger],
  'crud-form:projects.milestone:header': [operatingLoopTrigger],
  'crud-form:projects.risk:header': [operatingLoopTrigger],
  'detail:commercial.contract:header': [operatingLoopTrigger],
  'detail:commercial.invoice:header': [operatingLoopTrigger],
  'crud-form:commercial.payment:header': [operatingLoopTrigger],
  'crud-form:commercial.payment_allocation:header': [operatingLoopTrigger],
  'detail:insights.kpi_target:header': [operatingLoopTrigger],
  'detail:governance.finding:header': [operatingLoopTrigger],
  'crud-form:governance.identity_map:header': [operatingLoopTrigger],
}

export default injectionTable
